// File generated by FlutterFire configure.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtsoH2Ay5gg6DnuaSe1UxFm8mSs8VjW9g',
    appId: '1:126891448328:web:placeholder',
    messagingSenderId: '126891448328',
    projectId: 'flutter-project-19895',
    authDomain: 'flutter-project-19895.firebaseapp.com',
    storageBucket: 'flutter-project-19895.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlG-1OpHtcMN6CwUVl307aXrDpZwexY04',
    appId: '1:437080331346:android:55c8e6df5ee784fc587b8b',
    messagingSenderId: '437080331346',
    projectId: 'flutter-project-801d9',
    storageBucket: 'flutter-project-801d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9xiDOvbAqnkFiG7GFsHZh9X3kn49hxAs',
    appId: '1:437080331346:ios:c13d839952311144587b8b',
    messagingSenderId: '437080331346',
    projectId: 'flutter-project-801d9',
    storageBucket: 'flutter-project-801d9.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9xiDOvbAqnkFiG7GFsHZh9X3kn49hxAs',
    appId: '1:437080331346:ios:c13d839952311144587b8b',
    messagingSenderId: '437080331346',
    projectId: 'flutter-project-801d9',
    storageBucket: 'flutter-project-801d9.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );
}
